name: Build and Deploy to Tencent Cloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }}:latest
          # tags: your-dockerhub-username/your-repo-name:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Tencent Cloud CLI
        run: |
          curl -o- https://curl.qcloud.com/raw.githubusercontent.com/tencentcloud/tencentcloud-cli/master/install.sh | bash
          echo "$HOME/.tencentcloud/bin" >> $GITHUB_PATH
      - name: Login to Tencent Cloud CLI
        run: |
          tencentcloud configure set --region ap-guangzhou --secret-id ${{ secrets.TENCENT_CLOUD_SECRET_ID }} --secret-key ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
      - name: Pull and run Docker image on Tencent Cloud server
        run: |
          tencentcloud ssh lhins-9rogwy94 --command "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }}:latest && docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }}:latest"